required = [
    "github.com/aws/aws-sdk-go",
    "github.com/emicklei/go-restful",
    "github.com/onsi/ginkgo", # for test framework
    "github.com/onsi/gomega", # for test matchers
    "github.com/openshift/generic-admission-server/pkg/cmd",
    "github.com/stretchr/testify/assert",
    "golang.org/x/net/context",
    "github.com/openshift/installer/pkg/types",
    "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1",
    "k8s.io/apiserver/pkg/util/logs",
    "k8s.io/client-go/plugin/pkg/client/auth/gcp", # for development against gcp
    "k8s.io/code-generator/cmd/deepcopy-gen", # for go generate
    "sigs.k8s.io/controller-tools/cmd/controller-gen", # for crd/rbac generation
    "sigs.k8s.io/controller-runtime/pkg/client/config",
    "sigs.k8s.io/controller-runtime/pkg/controller",
    "sigs.k8s.io/controller-runtime/pkg/handler",
    "sigs.k8s.io/controller-runtime/pkg/manager",
    "sigs.k8s.io/controller-runtime/pkg/runtime/signals",
    "sigs.k8s.io/controller-runtime/pkg/source",
    "sigs.k8s.io/testing_frameworks/integration", # for integration testing
]

[prune]
  go-tests = true
  non-go = true
  unused-packages = true

# STANZAS BELOW ARE GENERATED AND MAY BE WRITTEN - DO NOT MODIFY BELOW THIS LINE.

[[constraint]]
  name="sigs.k8s.io/controller-runtime"
  version="v0.1.1"

[[constraint]]
  name="sigs.k8s.io/controller-tools"
  version="v0.1.1"

[[override]]
  name="k8s.io/api"
  version="kubernetes-1.11.2"

[[override]]
  name="k8s.io/apimachinery"
  version="kubernetes-1.11.2"

# For dependency below: Refer to issue https://github.com/golang/dep/issues/1799
[[override]]
name = "gopkg.in/fsnotify.v1"
source = "https://github.com/fsnotify/fsnotify.git"
version="v1.4.7"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.6"

[[override]]
  name = "k8s.io/client-go"
  version="kubernetes-1.11.2"

[[constraint]]
  name = "github.com/openshift/installer"
  revision = "4b9866659d277572a567e38074db7e5a926a5f55"

[[constraint]]
  name = "github.com/openshift/generic-admission-server"
  version = "v.1.11.0"

[[override]]
  name = "k8s.io/apiserver"
  version="kubernetes-1.11.2"

[[constraint]]
  branch = "master"
  name = "github.com/openshift/api"

[[constraint]]
  name = "sigs.k8s.io/cluster-api"
  branch = "master"

[[override]]
  name = "sigs.k8s.io/cluster-api-provider-aws"
  source = "https://github.com/openshift/cluster-api-provider-aws.git"
  branch = "master"

[[override]]
  name = "github.com/kubernetes-sigs/federation-v2"
  ## TODO: Revert to upstream when idempotent join is available
  source = "github.com/csrwng/federation-v2"
  branch = "idempotent_join"
