apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedNamespacePlacement
metadata:
  name: etcd-operator
  namespace: etcd-operator
spec:
  clusterSelector:
    matchLabels:
      etcdoperator: "yes"
