apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedClusterRoleBinding
metadata:
  name: etcd-operator
spec:
  template:
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: etcd-operator
    subjects:
    - kind: ServiceAccount
      name: default
      namespace: etcd-operator
