apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: clusterdeployments.hive.openshift.io
spec:
  group: hive.openshift.io
  names:
    kind: ClusterDeployment
    plural: clusterdeployments
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            baseDomain:
              type: string
            clusterID:
              type: string
            machines:
              items:
                properties:
                  name:
                    type: string
                  platform:
                    properties:
                      aws:
                        properties:
                          iamRoleName:
                            type: string
                          rootVolume:
                            properties:
                              iops:
                                format: int64
                                type: integer
                              size:
                                format: int64
                                type: integer
                              type:
                                type: string
                            required:
                            - iops
                            - size
                            - type
                            type: object
                          type:
                            type: string
                        required:
                        - type
                        - iamRoleName
                        - rootVolume
                        type: object
                    type: object
                  replicas:
                    format: int64
                    type: integer
                required:
                - name
                - replicas
                - platform
                type: object
              type: array
            networking:
              properties:
                podCIDR:
                  type: string
                serviceCIDR:
                  type: string
                type:
                  type: string
              required:
              - type
              - serviceCIDR
              - podCIDR
              type: object
            platform:
              properties:
                aws:
                  properties:
                    credentialsSecret:
                      type: object
                    region:
                      type: string
                    sshSecret:
                      type: object
                    vpcCIDRBlock:
                      type: string
                    vpcID:
                      type: string
                  required:
                  - region
                  - vpcID
                  - vpcCIDRBlock
                  - sshSecret
                  - credentialsSecret
                  type: object
              type: object
            pullSecret:
              type: string
          required:
          - clusterID
          - baseDomain
          - networking
          - machines
          - platform
          - pullSecret
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
