apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: clusterdeployments.hive.openshift.io
spec:
  group: hive.openshift.io
  names:
    kind: ClusterDeployment
    plural: clusterdeployments
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            clusterUUID:
              type: string
            config:
              properties:
                baseDomain:
                  type: string
                clusterID:
                  type: string
                machines:
                  items:
                    properties:
                      name:
                        type: string
                      platform:
                        properties:
                          aws:
                            properties:
                              amiID:
                                type: string
                              iamRoleName:
                                type: string
                              rootVolume:
                                properties:
                                  iops:
                                    format: int64
                                    type: integer
                                  size:
                                    format: int64
                                    type: integer
                                  type:
                                    type: string
                                required:
                                - iops
                                - size
                                - type
                                type: object
                              type:
                                type: string
                              zones:
                                items:
                                  type: string
                                type: array
                            required:
                            - type
                            - iamRoleName
                            - rootVolume
                            type: object
                          libvirt:
                            properties:
                              image:
                                type: string
                              imagePool:
                                type: string
                              imageVolume:
                                type: string
                            required:
                            - image
                            type: object
                          openstack:
                            properties:
                              rootVolume:
                                properties:
                                  iops:
                                    format: int64
                                    type: integer
                                  size:
                                    format: int64
                                    type: integer
                                  type:
                                    type: string
                                required:
                                - iops
                                - size
                                - type
                                type: object
                              type:
                                type: string
                            required:
                            - type
                            - rootVolume
                            type: object
                        type: object
                      replicas:
                        format: int64
                        type: integer
                    required:
                    - name
                    - replicas
                    - platform
                    type: object
                  type: array
                networking:
                  properties:
                    podCIDR:
                      type: string
                    serviceCIDR:
                      type: string
                    type:
                      type: string
                  required:
                  - type
                  - serviceCIDR
                  - podCIDR
                  type: object
                platform:
                  properties:
                    aws:
                      properties:
                        defaultMachinePlatform:
                          properties:
                            amiID:
                              type: string
                            iamRoleName:
                              type: string
                            rootVolume:
                              properties:
                                iops:
                                  format: int64
                                  type: integer
                                size:
                                  format: int64
                                  type: integer
                                type:
                                  type: string
                              required:
                              - iops
                              - size
                              - type
                              type: object
                            type:
                              type: string
                            zones:
                              items:
                                type: string
                              type: array
                          required:
                          - type
                          - iamRoleName
                          - rootVolume
                          type: object
                        region:
                          type: string
                        userTags:
                          type: object
                        vpcCIDRBlock:
                          type: string
                        vpcID:
                          type: string
                      required:
                      - region
                      - vpcID
                      - vpcCIDRBlock
                      type: object
                    libvirt:
                      properties:
                        URI:
                          type: string
                        defaultMachinePlatform:
                          properties:
                            image:
                              type: string
                            imagePool:
                              type: string
                            imageVolume:
                              type: string
                          required:
                          - image
                          type: object
                        masterIPs:
                          items:
                            format: byte
                            type: string
                          type: array
                        network:
                          properties:
                            if:
                              type: string
                            ipRange:
                              type: string
                            name:
                              type: string
                          required:
                          - name
                          - if
                          - ipRange
                          type: object
                      required:
                      - URI
                      - network
                      - masterIPs
                      type: object
                  type: object
                pullSecret:
                  type: object
                sshKey:
                  type: object
              required:
              - clusterID
              - baseDomain
              - networking
              - machines
              - platform
              - pullSecret
              type: object
            images:
              properties:
                hiveImage:
                  type: string
                hiveImagePullPolicy:
                  type: string
                installerImage:
                  type: string
                installerImagePullPolicy:
                  type: string
              required:
              - installerImage
              - installerImagePullPolicy
              - hiveImage
              - hiveImagePullPolicy
              type: object
            platformSecrets:
              properties:
                aws:
                  properties:
                    credentials:
                      type: object
                  required:
                  - credentials
                  type: object
              type: object
          required:
          - config
          - platformSecrets
          - images
          type: object
        status:
          properties:
            adminKubeconfigSecret:
              type: object
            apiURL:
              type: string
            installed:
              type: boolean
            webConsoleURL:
              type: string
          required:
          - installed
          - adminKubeconfigSecret
          - apiURL
          - webConsoleURL
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
