apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-operator
  namespace: openshift-hive
spec:
  template:
    spec:
      containers:
      # Run from a defined image published to quay as necessary for SD's needs:
      - image: IMAGE_REF
        imagePullPolicy: Always
        name: hive-operator
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 75Mi
        command:
          - /opt/services/hive-operator
          - --log-level
          - debug
      terminationGracePeriodSeconds: 10
---
apiVersion: hive.openshift.io/v1alpha1
kind: HiveConfig
metadata:
  name: hive
spec:
  image: IMAGE_REF
