---
# Scale mode only. Agent that brokers network traffic from the data plane to
# the control plane. This is only necessary for admission webhooks -- all other
# communication flows in the other direction.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: konnectivity-agent-hiveadmission
  # Replaced in code with the namespace of the data plane deployment.
  namespace: replace-target-namespace
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: konnectivity-agent
      hypershift.openshift.io/control-plane-component: konnectivity-agent
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: konnectivity-agent
        hypershift.openshift.io/control-plane-component: konnectivity-agent
    spec:
      automountServiceAccountToken: false
      containers:
      - args:
        - --logtostderr=true
        - --ca-cert
        - /etc/konnectivity/agent/ca.crt
        - --agent-cert
        - /etc/konnectivity/agent/tls.crt
        - --agent-key
        - /etc/konnectivity/agent/tls.key
        - --proxy-server-host
        - konnectivity-server
        - --proxy-server-port
        - "8091"
        - --health-server-port
        - "2041"
        - --agent-identifiers
        # Replaced in code with the hiveadmission Service IP
        - ipv4=replace-service-ip
        - --keepalive-time
        - 30s
        - --probe-interval
        - 30s
        - --sync-interval
        - 1m
        - --sync-interval-cap
        - 5m
        command:
        - /usr/bin/proxy-agent
        # Replaced in code with the image reference from the konnectivity-server
        # deployment in the target namespace. That image contains both server
        # and agent binaries.
        image: replace-konnectivity-server-image
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: healthz
            port: 2041
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 30
        name: konnectivity-agent
        resources:
          requests:
            cpu: 40m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/konnectivity/agent
          name: agent-certs
      dnsPolicy: ClusterFirst
      priorityClassName: hypershift-control-plane
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: hypershift.openshift.io/control-plane
        operator: Equal
        value: "true"
      volumes:
      - name: agent-certs
        secret:
          defaultMode: 420
          secretName: konnectivity-agent
