---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hiveapi-extension-apiserver-authentication-reader
  namespace: hive
roleRef:
  name: extension-apiserver-authentication-reader
  namespace: kube-system
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: hiveapi-sa
  namespace: hive

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hiveapi-auth-delegator
roleRef:
  name: system:auth-delegator
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: hiveapi-sa
    namespace: hive

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hiveapi-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-role
subjects:
- kind: ServiceAccount
  name: hiveapi-sa
  namespace: hive
