apiVersion: hive.openshift.io/v1alpha1
kind: ClusterImageSet
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: clusterimageset-sample
spec:
  hiveImage: registry.svc.ci.openshift.org/openshift/hive-v4.0:hive
  releaseImage: quay.io/openshift-release-dev/ocp-release:4.0.0-0.6
