apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-controllers
  namespace: openshift-hive
spec:
  template:
    spec:
      containers:
      # Run from a defined image published to quay as necessary for SD's needs:
      - name: manager
        image: quay.io/twiest/hive-controller:20190128
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 75Mi
        command:
          - /opt/services/manager
          - --log-level
          - debug
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hiveadmission
  namespace: openshift-hive
spec:
  template:
    spec:
      containers:
      - name: hiveadmission
        image: quay.io/twiest/hive-controller:20190128
        imagePullPolicy: Always
        command:
        - "/opt/services/hiveadmission"
        - "--secure-port=9443"
        - "--audit-log-path=-"
        - "--tls-cert-file=/var/serving-cert/tls.crt"
        - "--tls-private-key-file=/var/serving-cert/tls.key"
        - "--v=8"
        ports:
        - containerPort: 9443
        volumeMounts:
        - mountPath: /var/serving-cert
          name: serving-cert
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9443
            scheme: HTTPS
---
apiVersion: hive.openshift.io/v1alpha1
kind: HiveAdmissionConfig
metadata:
  name: hiveadmission
spec:
  image: quay.io/twiest/hive-controller:20190128
---
apiVersion: hive.openshift.io/v1alpha1
kind: HiveConfig
metadata:
  name: hive
spec:
  image: quay.io/twiest/hive-controller:20190128
