# Adds namespace to all resources.
namespace: openshift-hive

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
#namePrefix: openshift-hive-

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

# Each entry in this list must resolve to an existing
# resource definition in YAML.  These are the resource
# files that kustomize reads, modifies and emits as a
# YAML string, with resources separated by document
# markers ("---").
resources:
- ./namespace.yaml
- ./operator/operator_role.yaml
- ./operator/operator_role_binding.yaml
- ./operator/operator_deployment.yaml
