apiVersion: v1
kind: Template
metadata:
  name: additional-hive-regexes
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: additional-install-log-regexes
    data:
      regexes: |
        - name: EIPAddressLimitExceeded
          searchRegexStrings:
            - "EIP: AddressLimitExceeded"
          installFailingReason: EIPAddressLimitExceeded
          installFailingMessage: EIP Address limit exceeded
