apiVersion: v1
kind: ConfigMap
metadata:
  name: install-log-regexes
  namespace: hive
data:
  DNSAlreadyExists: |
    searchRegexStrings:
    - "aws_route53_record.*Error building changeset:.*Tried to create resource record set.*but it already exists"
    installFailingReason: DNSAlreadyExists
    installFailingMessage: DNS record already exists
  PendingVerification: |
    searchRegexStrings:
    - "PendingVerification: Your request for accessing resources in this region is being validated"
    installFailingReason: PendingVerification
    installFailingMessage: Account pending verification for region
  NoMatchingRoute53Zone: |
    searchRegexStrings:
    - "data.aws_route53_zone.public: no matching Route53Zone found"
    installFailingReason: NoMatchingRoute53Zone
    installFailingMessage: No matching Route53Zone found
  KubeAPIWaitTimeout: |
    searchRegexStrings:
    - "waiting for Kubernetes API: context deadline exceeded"
    installFailingReason: KubeAPIWaitTimeout
    installFailingMessage: Timeout waiting for the Kubernetes API to begin responding
